### ISSUE TITLE
test-only-66.2,not reproduce the results for kitti

### ISSUE THREAD

**Issue by deepearthgo** [kujason/avod#102]
Hi, i re-train the vgg-16-pyramid model, but get only 66.2% for car moderate, Is there any tips for reproduce the results for kitti-3d.

**Comment by applezoos** [comment]
Hi, I have same question. Recently, I'm doing job to compare famous 3D detection algorithms - AVOD, F-pointnet, second and so on. 
I could reproduce your validation results with train/val split dataset, but could not reproduce the test result (I tried to train with full training set, submit 3 times in kitti benchmark, and the moderate's AP values of car was between 64~66% ). And the code to generate ground plane that I used makes almost same values with the ground plane values in kitti training dataset.
I carefully checked all the options in the last arxiv paper. And for the options which are not in the paper, used default values in your code. If it is possible, could you let me know if there is any other things that I missed?

**Comment by Hub-Tian** [comment]
Any progress have you made? @genius07

**Comment by henrylee2570** [comment]
Similar problem here... @genius07 did you figure it out? Thank you!

**Comment by kujason** [comment]
#18
