### ISSUE TITLE
gen_mini_batches.py error

### ISSUE THREAD

**Issue by QZ1219** [kujason/avod#105]
FileNotFoundError: Dataset path does not exist:/root/Kitti/object  

Where can I  set dataset dir ?   I'm not skilful python

**Comment by ChengYiBin** [comment]
hello, do u solve this problem? your help will be very appreciate

**Comment by asvath** [comment]
I'm having the same issue. Any solution? Thanks!

**Comment by ChengYiBin** [comment]
I put the ‘Kitti’ directory in my home path, It's like /home/'user_name'/Kitti/
the Kitti dir is organized as the author described

**Comment by asvath** [comment]
Thanks @ChengYiBin ! 
I figured out that you can also put the Kitti directory anywhere you want, but you must edit kitti_dataset.py (avod/datasets/kitti).
Change the line : self.dataset_dir = os.path.expanduser(self.config.dataset_dir) to the path where your Kitti Directory is.

e.g self.dataset_dir ="/avod/Kitti/object"
