### ISSUE TITLE
gen_mini_batches  produce iou_2d/kitti/train/lidar/Car[0.5]/ *.npy

### ISSUE THREAD

**Issue by QZ1219** [kujason/avod#106]
*.npy      why we need these data ? what is  *.npy used for ?

Can someone give me some advices?  Thank you very much!

**Comment by Priyashbhugra** [comment]
please reply some one....i also have the same query

**Comment by Priyashbhugra** [comment]
.npy files are anchors...Read the working of Faster RCNN to understand anchors. @QZ1219
