### ISSUE TITLE
Different Projection Matrices in Kitti

### ISSUE THREAD

**Issue by Tar12** [kujason/avod#107]
Hi,

Anyone happens to know why images from the training/testing have different projection matrices P, to go from 3D annotations to image plane? Why would these be different (intrinsics?), leading to slightly different projection results/image sizes?

Thanks!

**Comment by kujason** [comment]
The KITTI samples were collected over multiple different days, and the cameras were re-calibrated each time data was collected, so they are sometimes slightly different.
