### ISSUE TITLE
Why anchor stride 0.5m?

### ISSUE THREAD

**Issue by bhyim516** [kujason/avod#108]
Hi.

I'm wondering why the anchor stride is 0.5m although the BEV resolution is 0.1m.

Because of the memory issue?

Isn't the stride of 0.1m better because of the small residue?

And does it align with the feature map in the last layer?

Thanks in advance.

**Comment by Benzlxs** [comment]
My opinion is that 0.1m resolution will generate too many anchors (25 times more) and consume too much GPU memory, and lead to infeasible training.
