### ISSUE TITLE
How to use multiple GPUs in training?

### ISSUE THREAD

**Issue by jackroos** [kujason/avod#109]
I want to use multiple GPUs to accelerate the training, and I run the training code with extra parameters '--device='0,1,2,3' '. But it seems just using one GPU for training. So how can I use more than one GPU to accelerate training? Thanks!

**Comment by ChengshuLi** [comment]
@kujason Any update on this issue? Thanks a lot!

**Comment by melfm** [comment]
Please refer to the tensorflow docs for [Using multiple GPUs](https://www.tensorflow.org/guide/using_gpu)

**Comment by Yamin05114** [comment]
@jackroos I am now working on the codes and I think currently it can not be trained on multiple GPUs unless you modify it to process batch number > 1. This work is actually a huge one, just look at original object detection api. So you know the answer.

**Comment by ZhengWG** [comment]
@jackroos  Do you have the solution now?

**Comment by kujason** [comment]
The code does not support multiple GPUs for training. If you have 2 GPUs, the code is written such that the training and evaluation scripts can be run in parallel with one GPU each.
