### ISSUE TITLE
ground plane 

### ISSUE THREAD

**Issue by kargarisaac** [kujason/avod#119]
Hi,
I want to train the network on Kitti. I don't want to use provided plane files. 
would you please explain about ground plane segmentation algorithm? Or is it possible to do the ground plane removal step before AVOD. I mean separate point clouds above the ground and feed them to AVOD. Which file I need to change?
Thank you

**Comment by WangGangUCAS** [comment]
where is the provided plane files?

**Comment by kargarisaac** [comment]
> where is the provided plane files?

https://drive.google.com/drive/folders/1yjCwlSOfAZoPNNqoMtWfEjPCfhRfJB-Z

they provided the link in the readme

**Comment by kujason** [comment]
#19
