### ISSUE TITLE
preprocessing time

### ISSUE THREAD

**Issue by yzhou-saic** [kujason/avod#12]
The preprocessing time is like:
Feed dict time:
Min:  0.12029
Max:  0.24133
Mean:  0.14371
Median:  0.14227
much larger than 0.02s reported ?

**Comment by kujason** [comment]
Preprocessing time includes the data preprocessing steps on the CPU, such as BEV and anchor generation, and will depend on your particular CPU. Data (images and velodyne points) loading time from the disk drive is not included and will also vary based on computer setup (CPU, with HDD or SSD). Normally, this data is provided directly from a ROS node when deployed. The `feed_dict` time that you are seeing includes both the data loading and preprocessing time.
