### ISSUE TITLE
For testing set

### ISSUE THREAD

**Issue by g95732000** [kujason/avod#120]
First, thanks for your provide code.
I want test my model on KITTI server but result is bad.
Is there any tips or something need to be careful or check?
Can you share your training experiment for testing?
thanks very much.

**Comment by mikon1995** [comment]
hi,have you tested the results on KITTI dataset? seems i meet the same issue. have you solved it yet?

**Comment by g95732000** [comment]
@mikon1995 Not yet, whether I train on 50/50 or custom 85/15 the performance on testing set still not good.

**Comment by mikon1995** [comment]
@g95732000 have you tried generate ground planes of each frame in testing set? the accuracy of avod seems depends on estimated planes heavily.

**Comment by g95732000** [comment]
@mikon1995 yes, I have

**Comment by arazvant** [comment]
> @mikon1995 yes, I have

Hey, could you please share what method have you used for generating ground planes of each frame?
It would be of much help

**Comment by kujason** [comment]
Planes #19
