### ISSUE TITLE
use AVOD in python 2

### ISSUE THREAD

**Issue by kargarisaac** [kujason/avod#121]
Hi,

I want to use AVOD with ROS1 and python2.
I followed the steps in the readme file without any problem, but when I want to run " python scripts/preprocessing/gen_mini_batches.py" in avod folder, I get the following error:

`
File "bev_generator.py", line 16, in <module>
    from avod.builders.dataset_builder import DatasetBuilder
  File "/home/isaac/catkin_ws/src/bev/avod/avod/builders/dataset_builder.py", line 14, in <module>
    from avod.protos import kitti_dataset_pb2
ImportError: No module named protos
`
the import part of dataset_builder.py is as follows:
```
import avod
from avod.datasets.kitti.kitti_dataset import KittiDataset
from avod.protos import kitti_dataset_pb2
from` avod.protos.kitti_dataset_pb2 import KittiDatasetConfig
```

I wonder why it knows `avod` and `avod.datasets.kitti.kitti_dataset` folders but doesn't know `avod.protos`.

Any suggestion?

Thank you

**Comment by ChunML** [comment]
Add a blank `__init__.py` inside `protos` folder (under `avod` folder) may do the trick.

**Comment by kargarisaac** [comment]
> Add a blank `__init__.py` inside `protos` folder (under `avod` folder) may do the trick.

Thank you. It worked!

**Comment by sgs678** [comment]
Will you still need to install ROS to run this code? I will be very grateful for your answer.

**Comment by ChunML** [comment]
You don't have to install ROS. In fact, the source code is written in Python 3.5, so it won't work with ROS. If you want to use the code with ROS, you have to make the source compatible with Python 2 first (which can be done easily) and make a ROS node for that.

**Comment by sgs678** [comment]
That's good, I hope so. Thank you for your answer.

**Comment by sgs678** [comment]
@ChunML  When I run  gen_mini_batches.py,I meet this error,do you know why ?Thank you!

 File "/home/scw4750/087/avod/wavedata/wavedata/tools/core/voxel_grid_2d.py", line 99, in voxelize_2d
    discrete_pts_2d.shape[0] - unique_indices[-1]) 
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by BojanAndonovski71** [comment]
hi. I would like to use this with ROS too. And is it possible to use the code with latest CUDA 10  and cuddn 7.1? Also this this code can give me the individual orientation in real time of the detected objects?
