### ISSUE TITLE
Multiclass Model

### ISSUE THREAD

**Issue by gabewb** [kujason/avod#122]
Any recommendations on how to train a model that handles Cars/Trucks/Bikes/Pedestrians in a single model? I've been playing a little with the IOU parameters, but the results are not so great.

**Comment by kargarisaac** [comment]
> Any recommendations on how to train a model that handles Cars/Trucks/Bikes/Pedestrians in a single model? I've been playing a little with the IOU parameters, but the results are not so great.

Same issue. There are some different configs mentioned in the paper. I think we have to fine tune them to use one config for all classes. But it is time-consuming. Please share if you found a way, ...

**Comment by kujason** [comment]
#57 #124
