### ISSUE TITLE
To start training，No checkpoints found

### ISSUE THREAD

**Issue by sgs678** [kujason/avod#126]
To start training, run the following:
python avod/experiments/run_training.py --pipeline_config=avod/configs/avod_cars_example.config
The following error occurred！！

No checkpoints found
Traceback (most recent call last):
  File "/home/scw4750/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/scw4750/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1310, in _run_fn
    self._extend_graph()
  File "/home/scw4750/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1358, in _extend_graph
    graph_def.SerializeToString(), status)
  File "/home/scw4750/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: MaxBytesInUse = MaxBytesInUse[]()]]

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: MaxBytesInUse = MaxBytesInUse[]()]]

**Comment by WUT-xiaoming** [comment]
me too

**Comment by BOLIN199** [comment]
you can 
pip uninstall tensorflow
pip install tensorflow-gpu
or set the device=0 in run_training.py

**Comment by WUT-xiaoming** [comment]
Thank you for your letter.
After a while, my code debugging ability has grown very fast, I have solved a lot of problems and can now run successfully.My tutor asked me to change the lidar point cloud input to right color images,I am a little confused, can I change the network like this?
Do I need to make a big change to the network?
My English is not good, please forgive me.
Looking forward to your reply






------------------ 原始邮件 ------------------
发件人: "BOLIN199"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 下午4:20
收件人: "kujason/avod"<avod@noreply.github.com>;
抄送: "1254305549"<1254305549@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [kujason/avod] To start training，No checkpoints found (#126)




you can
 pip uninstall tensorflow
 pip install tensorflow-gpu
 or set the device=0 in run_training.py

**Comment by WUT-xiaoming** [comment]
Thank you for your letter.After a while, my code debugging ability has grown very fast, I have solved a lot of problems and can now run successfully.




------------------ 原始邮件 ------------------
发件人: "BOLIN199"<notifications@github.com>; 
发送时间: 2019年5月6日(星期一) 下午4:20
收件人: "kujason/avod"<avod@noreply.github.com>; 
抄送: "1254305549"<1254305549@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [kujason/avod] To start training，No checkpoints found (#126)




you can
 pip uninstall tensorflow
 pip install tensorflow-gpu
 or set the device=0 in run_training.py
