### ISSUE TITLE
Replicating AP on Pedestrian and Cyclist classes

### ISSUE THREAD

**Issue by Fredrik00** [kujason/avod#128]
Hi, I am currently working on small modifications to the architecture and comparing performance, but I am having trouble replicating the results within a reasonable margin of error on the Cyclist and Pedestrian classes. I took it from the article that you used a single model to detect both these classes, and that the pyramid_people_example config would be the one used for this model, but the results are much worse especially for the Cyclist class. Did you train separate models to produce the results reported in the README, and in either case could you confirm or provide which config was used to produce these results?

**Comment by sgs678** [comment]
@Fredrik00 Hi,when you run the  gen_mini_batches.py,can you meet this error?

File "/home/scw4750/087/avod/wavedata/wavedata/tools/core/voxel_grid_2d.py", line 99, in voxelize_2d
discrete_pts_2d.shape[0] - unique_indices[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by kujason** [comment]
#123, #150
