### ISSUE TITLE
run_evaluation.py  error

### ISSUE THREAD

**Issue by sgs678** [kujason/avod#129]
ValueError: /...../zz/avod/avod/data/outputs/pyramid_cars_with_aug_example/checkpoints must have at least one checkpoint entry.

**Comment by sainisanjay** [comment]
@sgs678 did you solve the above error??? I am also getting exactly same error.

**Comment by ghkdtlghks77** [comment]
@sgs678 have you trained the model? the checkpoints are created every 1000 steps after you start training

**Comment by kujason** [comment]
Not enough information
