### ISSUE TITLE
I couldn't download  planes documents from the link-https://drive.google.com/open?id=1yjCwlSOfAZoPNNqoMtWfEjPCfhRfJB-Z?is there any other way to download it ?

### ISSUE THREAD

**Issue by yxy1995123** [kujason/avod#131]
I couldn't download  planes documents from the link-https://drive.google.com/open?id=1yjCwlSOfAZoPNNqoMtWfEjPCfhRfJB-Z?is there any other way to download it ?

**Comment by sainisanjay** [comment]
same problem to me.

**Comment by yxy1995123** [comment]
I think I find a solution.https://blog.csdn.net/weixin_39837709/article/details/79710962

**Comment by christian-lanius** [comment]
The correct link is https://drive.google.com/open?id=1yjCwlSOfAZoPNNqoMtWfEjPCfhRfJB-Z then, there is a planes folder.
