### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by yxy1995123** [kujason/avod#133]
In training process,there is a problem in trainer,py in line 98:InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: MaxBytesInUse = MaxBytesInUse[]()]]

how can I solve it ?

**Comment by lapetite123** [comment]
I got yje same problem as you, have you solved it?

**Comment by lapetite123** [comment]
I got the same error as you, have you solved it ?

**Comment by yxy1995123** [comment]
choose your GOU id.For example:gpu=0

**Comment by EKELE-NNOROM** [comment]
@yxy1995123 how do I choose the GOU id

**Comment by EKELE-NNOROM** [comment]
Thanks found it 'run_training.py' line 51, I set default_device = '0'. That solved it. I only have one GPU and it's id is 0

**Comment by WuYiYiYi** [comment]
I got the same error as you,but set default_device='0' do not solve it. How can I solve it?

**Comment by YongYongLi123** [comment]
Hello:
Have you solved this problem? I also encountered the same problem, I don't know if it is caused by insufficient GPU memory, mine is GTX1650 4G

**Comment by kujason** [comment]
`Registered devices: [CPU]` means that you are not using your GPU. Ensure that you have the GPU version of tensorflow installed:
```
pip uninstall tensorflow
pip install tensorflow-gpu==1.X.X
```
