### ISSUE TITLE
About plain equation: all_y = -(a * all_x + c * all_z + d) / b

### ISSUE THREAD

**Issue by placeforyiming** [kujason/avod#136]
Why we need the equation like this? I mean, the y for plain in terms of x and z can be interpreted as y=ax+bz+c, why we need four parameters here?

**Comment by kujason** [comment]
Yes, it is true that the plane coefficients can be represented with 3 values if desired. However, representing them as (a,b,c,d) is easier to understand and verify since they directly represent the plane's unit normal (a, b, c), and an offset distance (d)
