### ISSUE TITLE
kitti.py cann't be found.

### ISSUE THREAD

**Issue by LiuCKind** [kujason/avod#141]
Available steps: ['120000']
Prediction images saved to: /home/avod/avod/data/outputs/avod_cars_example/predictions/images_2d/predictions/val/120000/0.1
Saving 3769 / 3769, Avg Time: 0.471s, Time Remaining: 0.47s
Done

When I fininshed show_predictions_2d.py, I cann't find kitti.py to show my results. What can I do?

**Comment by kujason** [comment]
You can find the output images in the directory that is printed. There is no script to display these images.

**Comment by LiuCKind** [comment]
> You can find the output images in the directory that is printed. There is no script to display these images.

/home/avod/venv/bin/python /home/liuchengkan/avod/demos/generate_anchors.py
Anchors generated in 0.0003752708435058594 s
Anchors projected in 0.00037860870361328125 s

Process finished with exit code 0

Thanks for your reply. Then I run generate_anchors.py, but I just get one picture and there are no anchors. Is there anything wrong with the code? @kujason

**Comment by kujason** [comment]
The timing you show for the anchor generation and projection seem too fast, so something has likely been modified in the code, or some data is missing.
