### ISSUE TITLE
Can't find result_file.

### ISSUE THREAD

**Issue by LiuCKind** [kujason/avod#142]
# Output from native eval    
 results_file = 'results/pyramid_cars_with_aug_example_results_0.1.txt'
When I run plot_ap.py, I can't find this txt file. How can I make results visible？
Much appreciate!

**Comment by WuYiYiYi** [comment]
I have same question,can you solve it?

**Comment by WuYiYiYi** [comment]
@LiuCKind @kujason Can you help me?Thanks a lot!That file is empty.

**Comment by DGCHAO** [comment]
Find the floder of Kitti_native_eval, then find README.md. Where are the steps that teach you how to run

**Comment by chrisyan** [comment]
> Find the floder of Kitti_native_eval, then find README.md. Where are the steps that teach you how to run

Hi DGCHAO,
I have read the README.md in kitti_nativ_eval, but I am confused about the second step. It says "2. Copy the results folder into this folder. Each step should contain a 'data' folder."
However, I find this results folder in offline_eval is empty. Could you figure out this problem?
Thanks a lot!

**Comment by DGCHAO** [comment]
you should cd avod-master/avod/data/outputs/pyramid_cars_with_aug_example/predictions/kitti_native_eval/,then make it.Finally run all_eval.sh 0.1.

**Comment by chrisyan** [comment]
> you should cd avod-master/avod/data/outputs/pyramid_cars_with_aug_example/predictions/kitti_native_eval/,then make it.Finally run all_eval.sh 0.1.

Hi DGCHAO,
thanks for your reply. I find there are two paths that includes kitti_native_eval, it confuses me before.  Have a nice day!
