### ISSUE TITLE
anchor generation according to plane

### ISSUE THREAD

**Issue by yzl96** [kujason/avod#145]
I see your code:
a, b, c, d = ground_plane
all_x = before_sub[:, 0]
all_z = before_sub[:, 1]
all_y = -(a * all_x + c * all_z + d) / b

it looks like you just put the anchor center to the ground, but in your paper, the 3D anchor center seems to off the ground?

**Comment by kujason** [comment]
In the KITTI dataset, the convention of the box centroids are the bottom centre of the 3D box.
