### ISSUE TITLE
Is there a chance to use stereo Camera input for AVOD FPN? 

### ISSUE THREAD

**Issue by Bruslan** [kujason/avod#147]
I am talking about the second camera of Kitti dataset. I assume that a second camera would improve the prediction Score in Kitti-3D-Benchmark. Is there an option in AVOD to do that?

**Comment by kujason** [comment]
This is not currently set up in this code, but feel free to try it out. To do this, you would need to add an additional feature extractor and set up the corresponding projection, crop-and-resize, and fusion operations.

**Comment by Bruslan** [comment]
Nice thank you. Do i have to modify the mini batch creation too? I need this for my master thesis, and didnt know how and where in your code to start first. Would be kind if you could give me some advices.

**Comment by kujason** [comment]
Please see https://arxiv.org/pdf/1909.07566.pdf and https://arxiv.org/pdf/2003.05505.pdf for examples
