### ISSUE TITLE
How to realize the result  just like the avod detection video shows?

### ISSUE THREAD

**Issue by Buerzhu** [kujason/avod#149]
Hi,I had ran the kitty.py and the kitti_bev_vis.py,and got the results below:
![2](https://user-images.githubusercontent.com/48277531/62831394-160f8700-bc51-11e9-9456-6288219c4d20.png)
![4](https://user-images.githubusercontent.com/48277531/62831399-1f005880-bc51-11e9-9576-66ac04d12210.png)
It worked well with the providing label datas,but I want to know if there is a file can get the image datas and lidar datas as input(not use the label_2 datas) and have the output just like the avod detection video shows?I want to get  car's location infomation and rotation infomation

**Comment by kujason** [comment]
Visualization scripts are available at: https://github.com/kujason/scene_vis
You will need to modify them to suit your needs.
