### ISSUE TITLE
What are the planes *.bin files?

### ISSUE THREAD

**Issue by FranciscoGomez90** [kujason/avod#154]
I want to train AVOD on a different dataset. I have prepared the images, the lidar point clouds and the annotations. However, there is a planes folder that it seems i'm going to need.
Any clue about what they mean? How can they be computed?
Thanks!

**Comment by yinhai86924** [comment]
> I want to train AVOD on a different dataset. I have prepared the images, the lidar point clouds and the annotations. However, there is a planes folder that it seems i'm going to need.
> Any clue about what they mean? How can they be computed?
> Thanks!

I have the same problem, if I want to test dataset, I do not how to do it.

**Comment by kujason** [comment]
The "planes" folder contains files with the estimated ground plane for each sample. See #19 for more details.
