### ISSUE TITLE
evaluate question

### ISSUE THREAD

**Issue by Buerzhu** [kujason/avod#156]
Who knows how to evaluate a single checkpoint?

**Comment by 619862306** [comment]
@Buerzhu  I would appreciate if you can send me the pre-trained model.
My email address is : caoqi@hdu.edu.cn

**Comment by kujason** [comment]
You can use the `run_inference.py` to get predictions from a single checkpoint (https://github.com/kujason/avod#run-inference), and then call the `evaluate_object_3d_offline` script to get evaluation results.
