### ISSUE TITLE
Add timing chart to Wiki

### ISSUE THREAD

**Issue by kujason** [kujason/avod#16]
https://github.com/kujason/avod/wiki/Timing

**Comment by yzhou-saic** [comment]
Thanks for releasing the time table in wiki.
Are you using another set of code for preprocessing ? It seems preprocessing is indeed slow, I am confident that the cpu on my machine is powerful.
1) Could you possibly attach hardware settings for the reported time ?
2) Are you using intel MKL as the math library ?
3) I doubt the reported time table can align with the code, if the deployment code could be released, it could be quite helpful.
