### ISSUE TITLE
ImportError: No module named avod

### ISSUE THREAD

**Issue by chrisyan** [kujason/avod#160]
Hello everyone, now I wanna Mini-batch Generation. I used the command line 
"cd avod
python scripts/preprocessing/gen_mini_batches.py"

However, I got this ImportError
 "Traceback (most recent call last):
  File "scripts/preprocessing/gen_mini_batches.py", line 5, in <module>
    import avod
ImportError: No module named avod
"

Can anyone help me? Thanks!

Best,
Chris

**Comment by NoRomantic** [comment]
You need to add the avod and wavedata path to PYTHONPATH.
