### ISSUE TITLE
Can you tell me your configuration when you train the avod code ? My computer reboot when I train it in my GPU

### ISSUE THREAD

**Issue by daodaoling** [kujason/avod#161]

**Comment by daodaoling** [comment]
If you have trained it on your GPU smoothly,please help me.I need your GPU type , CUDA version,CUDNN version,tensorflow version,python version and other relevent information .I will be grateful if you can help .

**Comment by NoRomantic** [comment]
My GPU is P6000, CUDA V8.0.61 and CUDNN 7, tensorflow-gpu==1.3.0, python=3.5. These configurations are all the same as the author recommended. Also my os is ubuntu16.04.

**Comment by daodaoling** [comment]
Thank you for your help so much ! I will have a try .




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"NoRomantic"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 上午9:17
收件人:&nbsp;"kujason/avod"<avod@noreply.github.com&gt;;
抄送:&nbsp;"叨叨令"<1981415640@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kujason/avod] Can you tell me your configuration when you train the avod code ? My computer reboot when I train it in my GPU (#161)




My GPU is P6000, CUDA V8.0.61 and CUDNN 7, tensorflow-gpu==1.3.0, python=3.5. These configurations are all the same as the author recommended. Also my os is ubuntu16.04.

**Comment by daodaoling** [comment]
hello,thank you for your help last time .I followed your version suggested .And then I get another problem .I just install all it .My GPU is 2080 Ti and my NVIDIA driver is nvidia-430 。I installed all of them but when I run the mnist example&nbsp; ,it did not work.It run to some step and the computer crash&nbsp; ,I can not click to anything.I checked it and find the 32G memry of my computer has no free space and my GPU memery also has no memery .I checked the version and find the cuda8.0 can not match cudnn7. I think you may send a wrong version of them .Can you check all the related and send it to me again .I will be appreciated if you can help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"NoRomantic"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 上午9:17
收件人:&nbsp;"kujason/avod"<avod@noreply.github.com&gt;;
抄送:&nbsp;"叨叨令"<1981415640@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kujason/avod] Can you tell me your configuration when you train the avod code ? My computer reboot when I train it in my GPU (#161)




My GPU is P6000, CUDA V8.0.61 and CUDNN 7, tensorflow-gpu==1.3.0, python=3.5. These configurations are all the same as the author recommended. Also my os is ubuntu16.04.

**Comment by kujason** [comment]
Please check that you have correctly installed CUDA and NVIDIA drivers. The computer rebooting could be an issue related to your power supply.
