### ISSUE TITLE
No checkpoints found

### ISSUE THREAD

**Issue by DavidDiosdado** [kujason/avod#164]
I am trying to run the inference with some checkpoints I downloaded from the PseudoLidar repository. The files are:

- pyramid_cars_with_aug_example_scratch_300_val-00120000.data-00000-of-00001
- pyramid_cars_with_aug_example_scratch_300_val-00120000.index
- pyramid_cars_with_aug_example_scratch_300_val-00120000.meta

I put them into:

- `AVOD/avod/data/outputs/pyramid_cars_with_aug_example_scratch_300_val-00120000/checkpoints`

And placed the `pyramid_cars_with_aug_example_scratch_300_val-00120000.config` into the folder with the same name. The file name matches the checkpoint_name inside the config 

Then used the next line:

- `python avod/experiments/run_inference.py --checkpoint_name='pyramid_cars_with_aug_example_scratch_300_val-00120000' --data_split='test' --ckpt_indices=120 --device='1'`

This is the output:

```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:460: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:461: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:462: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:465: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/content/AVOD/avod/data/outputs/pyramid_cars_with_aug_example_scratch_300_val-00120000/pyramid_cars_with_aug_example_scratch_300_val-00120000.config
2020-01-10 22:31:11.976810: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2020-01-10 22:31:11.976906: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2020-01-10 22:31:11.976919: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2020-01-10 22:31:11.976944: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2020-01-10 22:31:11.976954: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
No checkpoints found
Traceback (most recent call last):
  File "avod/experiments/run_inference.py", line 136, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "avod/experiments/run_inference.py", line 132, in main
    args.ckpt_indices)
  File "avod/experiments/run_inference.py", line 71, in inference
    model_evaluator.run_latest_checkpoints()
  File "/content/AVOD/avod/core/evaluator.py", line 373, in run_latest_checkpoints
    checkpoint_to_restore = self._saver.last_checkpoints[ckpt_idx]
IndexError: list index out of range
```
Working on Google Colab with python 3 and tensorflow 1.3

What am I doing wrong? Thank you for your help

**Comment by sarimmehdi** [comment]
Hello. Were you able to solve this issue?

**Comment by DavidDiosdado** [comment]
No, I have been stucked with this error for over 2 months :/

> Hello. Were you able to solve this issue?

**Comment by Jossome** [comment]
I think I solved this problem. I'm also using some downloaded pretrained weights in the three files you mentioned.

At first, I had the same issue in [#132 ](https://github.com/kujason/avod/issues/132), so I manually set [this line](https://github.com/kujason/avod/blob/b7dcf31e50230c67bcf19ed063549a8b1bc4a785/avod/core/evaluator.py#L437 
) to `num_checkpoints = 1`

Then I had the same issue as yours. So I manually set [this line](https://github.com/kujason/avod/blob/b7dcf31e50230c67bcf19ed063549a8b1bc4a785/avod/core/evaluator.py#L449) as `"PATH_TO_CKPT/checkpoint_name"`. The `checkpoint_name` in your case should be `pyramid_cars_with_aug_example_scratch_300_val-00120000` without any extension, and `PATH_TO_CKPT` should be the path you put these three files in.

Then I'm able to load the checkpoint and run evaluations.

--------
Updates: well, I saw that your error is on a different line, but I think these two things are the same. You just manually set the path to your checkpoints.

**Comment by kkk324** [comment]
> I think I solved this problem. I'm also using some downloaded pretrained weights in the three files you mentioned.
> 
> At first, I had the same issue in [#132 ](https://github.com/kujason/avod/issues/132), so I manually set [this line](https://github.com/kujason/avod/blob/b7dcf31e50230c67bcf19ed063549a8b1bc4a785/avod/core/evaluator.py#L437) to `num_checkpoints = 1`
> 
> Then I had the same issue as yours. So I manually set [this line](https://github.com/kujason/avod/blob/b7dcf31e50230c67bcf19ed063549a8b1bc4a785/avod/core/evaluator.py#L449) as `"PATH_TO_CKPT/checkpoint_name"`. The `checkpoint_name` in your case should be `pyramid_cars_with_aug_example_scratch_300_val-00120000` without any extension, and `PATH_TO_CKPT` should be the path you put these three files in.
> 
> Then I'm able to load the checkpoint and run evaluations.
> 
> Updates: well, I saw that your error is on a different line, but I think these two things are the same. You just manually set the path to your checkpoints.

Work!

**Comment by 2892510130** [comment]
> PseudoLidar repository.

Hi! I wonder where you download these checkpoints from.
