### ISSUE TITLE
Issues with Evaluation Script

### ISSUE THREAD

**Issue by jmiemirza** [kujason/avod#169]
Hi, 

I have been using a new dataset but it has been built on the same format as KITTI. I am having trouble with the evaluation script. When I run the evaluation script to evaluate all the checkpoints, nothing is written in the results file. I am attaching a screenshot: 

![image](https://user-images.githubusercontent.com/50660423/78041924-a54ce480-7371-11ea-8d90-aa5d48b07849.png)

This is how it looks. However, I tried with just 50 samples of the same dataset and it provided me with the following output file: 

![image](https://user-images.githubusercontent.com/50660423/78042108-e04f1800-7371-11ea-9407-1369e66c1250.png)

Now when I follow the readme and evaluate individual checkpoints, I get only the Car Detection AP. 

Did anyone have the same problem? 

Thanks

**Comment by ferdyandannes** [comment]
> Hi,
> 
> I have been using a new dataset but it has been built on the same format as KITTI. I am having trouble with the evaluation script. When I run the evaluation script to evaluate all the checkpoints, nothing is written in the results file. I am attaching a screenshot:
> 
> ![image](https://user-images.githubusercontent.com/50660423/78041924-a54ce480-7371-11ea-8d90-aa5d48b07849.png)
> 
> This is how it looks. However, I tried with just 50 samples of the same dataset and it provided me with the following output file:
> 
> ![image](https://user-images.githubusercontent.com/50660423/78042108-e04f1800-7371-11ea-9407-1369e66c1250.png)
> 
> Now when I follow the readme and evaluate individual checkpoints, I get only the Car Detection AP.
> 
> Did anyone have the same problem?
> 
> Thanks

Have you solved this problem?
Because I have same problem, thank you

**Comment by kujason** [comment]
Please try compiling and running the C++ evaluation script separately (https://github.com/kujason/avod/tree/master/scripts/offline_eval/kitti_native_eval) to make sure it runs as expected.
