### ISSUE TITLE
Is it possible to use with ROS and  latest CUDA 10  and cuddn 7.1?

### ISSUE THREAD

**Issue by BojanAndonovski71** [kujason/avod#171]
hi. I would like to use this with ROS too. And is it possible to use the code with latest CUDA 10  and cuddn 7.1? Also this this code can give me the individual orientation in real time of the detected objects?

**Comment by kujason** [comment]
- We have used ROS to deploy this model before, it would just involve making a node to call the model inference
- Using CUDA 10 and CUDNN 7.1 should be fine
- Yes, the model outputs orientated bounding boxes
