### ISSUE TITLE
I am unable to clone the repository .. why?

### ISSUE THREAD

**Issue by MohamedAboushnief** [kujason/avod#173]
I use this command `git clone git@github.com:kujason/avod.git --recurse-submodules` to clone the repo but I get this error

```
Cloning into 'avod'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

why?

**Comment by sli057** [comment]
Same here...

**Comment by kujason** [comment]
This is probably because you don't have an ssh key set up. You can clone using HTTPS instead:
```
git clone https://github.com/kujason/avod.git
git submodule update --init --recursive
```

**Comment by sli057** [comment]
Thanks for the quick response!
The first command works, but the second command failed with the following info.

fatal: clone of 'git@github.com:kujason/wavedata.git' into submodule path '/Users/Shasha/Documents/avod/wavedata' failed
Failed to clone 'wavedata'. Retry scheduled
Cloning into '/Users/Shasha/Documents/avod/wavedata'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Any suggestions? Thanks!

**Comment by kujason** [comment]
Try changing the url for the wavedata submodule in `.gitmodules` to the HTTPS version:
https://github.com/kujason/wavedata.git

**Comment by sli057** [comment]
It works! Thanks for the quick and helpful response.
