### ISSUE TITLE
Inference Speed

### ISSUE THREAD

**Issue by linchunmian** [kujason/avod#174]
Hi author, thanks for your great job. As for autonomous driving, detection speed is an essential factor for  practical application. So I wonder how fast can AVOD achieve, and could you please explain it in detail? Like CPU setting, GPU type and memory, input size and other variance that maybe influence inference speed... 

I see speed information in this repository, however, I cannot reproduce similar result in my local computer. Therefore, I wonder it maybe caused by my PC setting.

Thanks in advance!

**Comment by kujason** [comment]
i7-7th gen, Titan Xp GPU
Your timing will likely be different unless you have exactly the same hardware.
