### ISSUE TITLE
How to evaluate the module on testing set?

### ISSUE THREAD

**Issue by 619862306** [kujason/avod#175]
I started research on 3d detection recently, now i have trained the avod-fpn module, and i find the input must have (bev_input & image & plane_anchors), but the testing set don't have plane, how do i evaluate the module on testing set?

**Comment by sjsjsjsj01** [comment]
> I started research on 3d detection recently, now i have trained the avod-fpn module, and i find the input must have (bev_input & image & plane_anchors), but the testing set don't have plane, how do i evaluate the module on testing set?

Hi, have you figured out how to test the model on the test set without planes?
