### ISSUE TITLE
confused: different image scales, if all images resized to the same scale,what about the gt bbox in image?

### ISSUE THREAD

**Issue by liyang0522** [kujason/avod#179]
the image scale in kitti  dataset is different , there are many scales,such as  (374, 1238, 3) , (375, 1242, 3), (370, 1224, 3),(376, 1241, 3),if all image scales are resized to the same, the gt bbox coordinates in image changed, how to deal with this issue?Thank you for helping me !

**Comment by kujason** [comment]
The ground truth bounding box coordinates are normalized by the image height and width, so different image resolutions are all supported.

**Comment by liyang0522** [comment]
Thank you for your rely! Could  you  please point where the code is?    I want to learn from it ! Thank you!!!

**Comment by kujason** [comment]
The normalization takes place in several places, mostly in the `_projector.py` files, which allows the boxes to be used by `tf.image.crop_and_resize` e.g. https://github.com/kujason/avod/blob/master/avod/core/anchor_projector.py#L153
For training this network, we only check overlap with ground truth in the bird's eye view:
https://github.com/kujason/avod/blob/master/avod/core/box_3d_projector.py#L78
