### ISSUE TITLE
Results on testing split

### ISSUE THREAD

**Issue by sshaoshuai** [kujason/avod#18]
Hi, 
Thanks for your great codes.
I run your codes with pyramid_cars_with_aug_example configuration, and final get the AP about (84.0, 74.0, 67.7) on val split, which is comparable with the results on your paper.
But when I use the best model to run on the test split, and I only get AP 56.4 on moderate split from the official testing service.
So do you know where is the problem?
Thanks very much.

**Comment by melfm** [comment]
We used the 50-50 split on the validation for a fair comparison with other methods, however for the submission to the test server, we used our own custom 85-15 split. We highly recommend you create your own custom split as well for submitting.

**Comment by sshaoshuai** [comment]
I see, thanks for your response.

**Comment by guduzxc** [comment]
Hi,
Thanks for your sharing. I have a configuration problem for obtaining the best validation results. To get the presented  AP (84, 74, 68) on val dataset, which model_name should I choose, avod_model or RPN model？I find that the default model name is avod_model, when should I set it to rpn_model in order to get the presented accuracy. Actually I'm a little confused by rpn_model.py and avod_model.py.

**Comment by guduzxc** [comment]
I  change the default config to pyramid_cars_with_aug_example.config for the training and validation, but I only got car_detection_3D AP: 82.906799 73.472794 67.455826 at checkpoint 100000, which is still much lower than the paper presented, so is there any other default configs should be changed?

**Comment by hulaifeng** [comment]
@ @melfm  create_train_test_txt.py
Could you please send the val.txt and training.txt of car ,pedestrian,cyclist to me? Here's my email: 201221100501@std.uestc.edu.cn 
thanks

**Comment by tilltheworldend** [comment]
@sshaoshuai Hi.I run the codes with pyramid_cars_with_aug_example configuration and didn't change any parameters in it.But I only got （76.8，72.4，66.9）ap using the 120000 checkpoint.Do you know why cause this?
