### ISSUE TITLE
How the planes is generated?

### ISSUE THREAD

**Issue by memoiry** [kujason/avod#19]
Hi

The project provided a planes directory for model's input. I'm a little curious about the way it was generated and It seems cannot be found in the paper. Could you please suggest some related resources? Thanks!

**Comment by asharakeh** [comment]
@memoiry for ground plane generation, we used a mixture of older methods that are probably considered obsolete now:

1. Ground segmentation and occupancy grid generation using probability fields:
https://www.researchgate.net/profile/Ali_Harakeh2/publication/282866885_Ground_Segmentation_and_Occupancy_Grid_Generation_Using_Probability_Fields/links/56baf64008ae0a6bc9557788/Ground-Segmentation-and-Occupancy-Grid-Generation-Using-Probability-Fields.pdf

2. http://www.cs.toronto.edu/objprop3d/

**Comment by yzhou-saic** [comment]
It looks like the ground plane algorithm is a little time-consuming, is that only the kitti testing, you are using this ground plane detection.
But when you are really deploying the model, it is a different story, for example, you are using a fixed ground plane ?

**Comment by asharakeh** [comment]
Yes for deployment, we do constant ground plane to eliminate the time required for estimation. It works well in practice for deployment,  but I doubt it to be a good approach for beating the KITTI benchmark.

**Comment by memoiry** [comment]
Thanks, my issue is solved

**Comment by hulaifeng** [comment]
@ @memoiry @yzhou-saic  Have you solved the problem of ground plane  about the test set?

**Comment by lucasjinreal** [comment]
@hulaifeng @asharakeh  So, how to generate the ground plane when testing?

**Comment by hulaifeng** [comment]
@jinfagang http://www.cs.toronto.edu/objprop3d/

**Comment by kargarisaac** [comment]
is it possible to do ground removing before AVOD and feed the points without ground into AVOD model? Is there any flag to disable using ground plane in AVOD?

**Comment by WangGangUCAS** [comment]
> Thanks, my issue is solved

how to solve it?thank you

**Comment by stomachacheGE** [comment]
> @memoiry for ground plane generation, we used a mixture of older methods that are probably considered obsolete now:
> 
> 1. Ground segmentation and occupancy grid generation using probability fields:
>    https://www.researchgate.net/profile/Ali_Harakeh2/publication/282866885_Ground_Segmentation_and_Occupancy_Grid_Generation_Using_Probability_Fields/links/56baf64008ae0a6bc9557788/Ground-Segmentation-and-Occupancy-Grid-Generation-Using-Probability-Fields.pdf
> 2. http://www.cs.toronto.edu/objprop3d/

The second link is dead. Could you please update?

**Comment by kkk324** [comment]
The second link is dead and planes in README is also dead.

**Comment by zwqnju** [comment]
> 2\. http://www.cs.toronto.edu/objprop3d/

I see the page in [this link](https://web.archive.org/web/20190106151141/http://www.cs.toronto.edu/objprop3d/)
