### ISSUE TITLE
protoc version

### ISSUE THREAD

**Issue by kzkmnmr** [kujason/avod#2]
Which version of "protoc" are you using in this project?

I got below error
> avod/protos/kitti_utils.proto:24:5: Expected "required", "optional", or "repeated".
avod/protos/kitti_utils.proto:24:25: Missing field number.
avod/protos/kitti_dataset.proto: Import "avod/protos/kitti_utils.proto" was not found or had errors.
avod/protos/kitti_dataset.proto:39:14: "KittiUtilsConfig" is not defined.

**Comment by melfm** [comment]
We are using protoc version `2.6.1`.

**Comment by kzkmnmr** [comment]
Thanks.
Actually, I'm working on Ubuntu14.04.

**Comment by a3VonG** [comment]
I'm having the same error, @kzkmnmr  how did you solve this issue?

**Comment by kzkmnmr** [comment]
@a3VonG you may try these command

`sudo apt-get update`
`sudo apt-get install libprotobuf-dev libprotoc-dev protobuf-compiler`

Actually, I got other error, so I changed to use Ubuntu16.04.

**Comment by chrisjuniorli** [comment]
@kzkmnmr do you know any other way to fix this error without changing to use Ubuntu 16.04? Thanks
