### ISSUE TITLE
Questions about 2D detection performance

### ISSUE THREAD

**Issue by AramSo** [kujason/avod#22]
First of all, congratulations on your good paper and code release.

According to your paper, many problems that existed in existing 2d box recognition have been solved. But I am curious. Why is the 2d box recognition rate not ranked at the top from kitti? ( Compared to methods that do not use point clouds)

I am curious to see if there is any limit to this lidar technique about 2d detections.

**Comment by AramSo** [comment]
Of couse, I think the test data has a lot of information in rgb. It looks favorable to rgb. However, if you have test data in a dark environment, the results are likely to change.

**Comment by melfm** [comment]
This might be related to two factors:

1. High ranking 2D detectors have been tailored and trained on 2D data. In terms of accuracy, it's an easier problem. Having said that, there is no good reason why a 3D detection should perform worse.

2. More important factor -> Many of the 2D detectors have usually been pre-trained on large image data-sets such as ImageNet. This will significantly affect the performance of the detection, specially the image branch. Take F-PointNet for instance, they pre-trained their 2D detector on ImageNet for 6 days. Of course this will improve the performance of 2D detection.
