### ISSUE TITLE
cannot found planes

### ISSUE THREAD

**Issue by tseliwang** [kujason/avod#25]
Excuse me for interrupting you. I`m trying to use your code. When I start training,  i cannot find the file named "planes",however i had been downloaded all Dataset from "http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=bev".
Could you please tell me the Website where i can download the "planes", thank you so much.

**Comment by melfm** [comment]
Planes for train and val set are provided [here](https://drive.google.com/open?id=1yjCwlSOfAZoPNNqoMtWfEjPCfhRfJB-Z)
