### ISSUE TITLE
Questions about continue training  from the last checkpoint

### ISSUE THREAD

**Issue by ch-lai** [kujason/avod#26]
First of all, thank you for sharing your brilliant work.

When setting "overwrite_checkpoints: False" in the config, it means if you stop at any checkpoint and later you want to train with more iterations it will start from the last checkpoint you saved.

Here are my questions, 
1. How do you perform deciding the order of input data?
2. When continue training from last checkpoint, will the input data order be initialized?

**Comment by kujason** [comment]
1. Samples are shuffled randomly at the start of each epoch for training. Samples are inferenced in their original order for validation and testing. This is handled by `create_feed_dict` in `rpn_model.py`
2. When continuing training from a previous checkpoint, the training data is shuffled in the same way as 1.
