### ISSUE TITLE
Why VGG 16 and not ResNet ?

### ISSUE THREAD

**Issue by Oussamab21** [kujason/avod#27]
Hello ,Thank you for sharing the code of this great work 
Why did you choose to use VGG16 as encoder instead of ResNet ?
Are you using Batch normalization ?
Another question how can we calculate the distance to the obstacles using the Lidar Points representation ? 
Thank you

**Comment by asharakeh** [comment]
Keep in mind that unlike most other methods, we aimed to have our work deployable on real vehicles not just tested on KITTI. We tried a ResNet feature extractor, it consumed way more memory and was actually a bit slower than our VGG varient. 

You are welcome to play around with the feature extractor to see if you can get better results than our FPN version.

**Comment by memoiry** [comment]
@asharakeh Thanks for the clarification! Have you tried using mobileNets for further accelerating?
