### ISSUE TITLE
what's the meaning of Plane?

### ISSUE THREAD

**Issue by HandsLing** [kujason/avod#31]
Width 4
Height 1
-5.445015e-02 -9.985028e-01 5.238001e-03 1.661760e+00
the four number stand for what?
thx

**Comment by bensondou** [comment]
It is plane coefficients [a, b, c, d] such that ax+by+cz+d = 0 for any 3D point on the plane. You can refer to some wiki pages for more details.

**Comment by Manyunze** [comment]
@bensondou @asharakeh  Hi, could you please tell me which XYZ coordinate does this plane matrix use, the velodyne coordinate or the camera (unrectified) one? Or I just want to know which axis is for depth direction.

Thanks!
