### ISSUE TITLE
I can't find the results 

### ISSUE THREAD

**Issue by Oussamab21** [kujason/avod#33]
After training and running the evaluation I can't find the results file 

FileNotFoundError: [Errno 2] No such file or directory: 'results/avod_cars_example_results_0.1.txt' 

so I am wondering what is the problem?,  your help will be much appreciated because I am working on my master's Thesis

**Comment by kujason** [comment]
Please check that you have g++ and libboost installed on your system

**Comment by melfm** [comment]
It looks like the native evaluation code is not being run properly, please follow the instructions [here](https://github.com/kujason/avod/tree/master/scripts/offline_eval/kitti_native_eval) to run this manually.
