### ISSUE TITLE
calculate AP

### ISSUE THREAD

**Issue by HandsLing** [kujason/avod#4]
the test set of KITTI dataset did not provide labels, How did you get the AP in your ablation experiment？

**Comment by melfm** [comment]
The results are submitted to the Kitti test server and evaluated there, please see [Kitti benchmark](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d)

**Comment by kujason** [comment]
The AP values reported in the ablation experiments are on the provided validation split (val.txt).

**Comment by HandsLing** [comment]
thanks
