### ISSUE TITLE
Only recall objects in the right side

### ISSUE THREAD

**Issue by electricmanlpl** [kujason/avod#40]
Hi, thanks for your sharing. I have trained and validated your network in kitti object train/val split, it works great.
However, when I test the network on kitti raw dataset, it gives out the below results. Only the right side objects are detected in the whole sequence.
![avod](https://user-images.githubusercontent.com/6188188/38912630-fa1fcae0-4308-11e8-8ea4-3990516dd2a4.png)
So any clues for pointing out the possible reason?

**Comment by griffintin** [comment]
@electricmanlpl 
I also trained and validated the network by train/val split, everything works great. By the way, traing data of ground plane is using the provided data. 
When I inferenced test images by using fixed ground plane [0, -1, 0, 1.65],  no car could be detected. 

how about the ground plane used for testing in your case?
