### ISSUE TITLE
Question on card with low VRAM

### ISSUE THREAD

**Issue by flomed** [kujason/avod#43]
Hey, my graphics card only has 2GB of VRAM is there anyway I can change the batch size for the training to work. I always get an error saying tensorflow ran out of memory. I've changed some settings in the configs but can't seem to get it to work. Or can someone maybe please upload a pretrained model I just wanted to test a few things.

Thanks

**Comment by asharakeh** [comment]
Even with trained model, there is no way you can run this architecture on a GPU with < 4GB memory.

**Comment by flomed** [comment]
Ok thanks for the info.
