### ISSUE TITLE
Can we have less than 12000 iterations?

### ISSUE THREAD

**Issue by Oussamab21** [kujason/avod#45]
I am training this model and I have a slow gpu I wonder if I will have the some network performances if I cut the training to 9000 or 8000 with step of 50 ?if there any harm in that ? 
because training + evaluation takes almost 54 hours for me 

another question why there is no max element wise fusion option for RPN model and how "late" and "deep" fusion types perform in comparison to "early" fusion?
Thank you

**Comment by YaduKini** [comment]
If you have got an answer to your question, could you please let me know?

**Comment by kujason** [comment]
The best performing model may not be the final one at 120,000 iterations. You can use the `plot_ap.py` to check the validation performance and help select the best model.
