### ISSUE TITLE
SyntaxError when executing gen_mini_batches.py

### ISSUE THREAD

**Issue by TuanHo16** [kujason/avod#48]
Hi,

Thank you for making your code available.

I follow your instruction in the front page but have encountered a syntax error while invoking the `gen_mini_batches.py` script as below.

Would you mind letting me know what I could do wrong?

```
tuan@mypc:~/avod$ python scripts/preprocessing/gen_mini_batches.py
Traceback (most recent call last):
  File "scripts/preprocessing/gen_mini_batches.py", line 6, in <module>
    from avod.builders.dataset_builder import DatasetBuilder
  File "avod/avod/builders/dataset_builder.py", line 169
    new_cfg=None) -> KittiDataset:
                  ^
SyntaxError: invalid syntax
```
Code retrieved in 5/11/2018.

Python version
```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
````
Kitti data structure as instructed as:

> Download the data and place it in your home folder at ~/Kitti/object

```
tuan@mypc:~/Kitti/object$ tree -L 2
.
├── training
│   ├── calib -> /opt/dataset/KITTI_3D/calib/training/calib
│   ├── image_2 -> /opt/dataset/KITTI_3D/image_2/training/image_2
│   ├── planes
│   └── velodyne -> /opt/dataset/KITTI_3D/velodyne/training/velodyne
├── train.txt
├── trainval.txt
└── val.txt
```

Ubuntu 16.04 LTS
GPU: nVidia 1080 Ti

Regards,
Tuan

**Comment by melfm** [comment]
Please read the requirements, you need `Python 3.5`.

**Comment by TuanHo16** [comment]
Thanks for your reply.

I am new to python, so I thought that your intention to run python 2 : 

> python scripts/preprocessing/gen_mini_batches.py

it works after changeing from python to python3
```
python3 scripts/preprocessing/gen_mini_batches.py
```

**Comment by melfm** [comment]
No problem!

**Comment by sgs678** [comment]
@melfm  When I run gen_mini_batches.py,I meet this error,do you know why ?Thank you!

File "/home/scw4750/087/avod/wavedata/wavedata/tools/core/voxel_grid_2d.py", line 99, in voxelize_2d
discrete_pts_2d.shape[0] - unique_indices[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0
