### ISSUE TITLE
After running demos/show_predictions_2d.py, nothing output!!!

### ISSUE THREAD

**Issue by lihua213** [kujason/avod#50]
To visualize these results, after running demos/show_predictions_2d.py. I only get two same images without 3D bounding box.
My system is:
ubuntu 16.04
Tensorflow 1.6
CUDA 9
Cudnn 7
Who can help me? Thanks in advance!

**Comment by lihua213** [comment]
![000015](https://user-images.githubusercontent.com/19219306/40099994-4f6997cc-591d-11e8-895d-37633f17334b.png)

**Comment by kujason** [comment]
Hi @lihua213, do you have images from other samples? Some predictions are not visualized due to their bounding box being truncated in the image.

**Comment by lihua213** [comment]
Thanks, @kujason, I tried the other samples and got the same output. Does it affect by different tensorflow version?
