### ISSUE TITLE
BEV map

### ISSUE THREAD

**Issue by karaspd** [kujason/avod#53]
Hi, thank you for sharing your code. I have a basic question regarding BEV map representation. From the code, it is the list of height map and array of density map. Can some one describe height map and what are the 5 slices? Also some reference to a paper or article would be great. 

In addition, how do you calculate ground plane downloaded from [here](https://drive.google.com/drive/folders/1yjCwlSOfAZoPNNqoMtWfEjPCfhRfJB-Z).
Thank you

**Comment by melfm** [comment]
This is also explained by [MV3D](https://arxiv.org/abs/1611.07759). You could also refer to my [thesis](https://github.com/melfm/masters_thesis), where I explain a bit more in detail.

Ground-plane estimation has been discussed in this issue #19.

**Comment by karaspd** [comment]
Thank you @melfm
