### ISSUE TITLE
Fail to use Protobufs to configure model and training parameters

### ISSUE THREAD

**Issue by liye228** [kujason/avod#54]
hello! 
I fail to use Protobufs to configure model and training parameters by using "sh avod/protos/run_protoc.sh" or "protoc avod/protos/*.proto --python_out=."
Please help me!
the error messages are as follow:
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: avod/protos/pipeline.proto.Compiling protos in /media/ubuntue/extdisk1/liye/avod-master/avod/protos
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: avod/protos/kitti_dataset.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: avod/protos/kitti_utils.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)

**Comment by chrisjuniorli** [comment]
@liye228  write the line ' syntax = "proto2" ' into every .proto file it mentioned above.

**Comment by liye228** [comment]
thanks

**Comment by YangBain** [comment]
@liye228 I have the same error you. So do you know how to solve it. Just like above said, i should put ' syntax = "proto2" in where in the each file. Thanks.

**Comment by liye228** [comment]
write the line ' syntax = "proto2" ' into every .proto file it mentioned above.

**Comment by YangBain** [comment]
I mean where should i put this sentence in each file. I revise my proto file, but there still are some errors. Thanks.

**Comment by liye228** [comment]
first line in each file

**Comment by YangBain** [comment]
Thank you very much. I get it.

**Comment by liye228** [comment]
@YangBain  Have you download the KITTI dataset ? If have you downloaded it, can you give me some help?
