### ISSUE TITLE
3-D Car Prediction Results

### ISSUE THREAD

**Issue by drNoob13** [kujason/avod#56]
Hi,

I have run the training/evaluation on the 'train' split and inference on the 'val' split.

Would you mind letting me know if the result my run (of `scripts/offline_eval/plot_ap.py`) is consistent with yours? I understand the numbers can fluctuate a bit. I just would like to know the range of values generated from my running is correct or not.

I use the `pyramid_cars_with_aug_example.cfg`.

![ap_pyramid_cars_with_aug_example_results_0 1 txt](https://user-images.githubusercontent.com/21091886/40333386-d9b7e632-5d1d-11e8-91ff-9652a852a37b.png)
```
car_detection             [ 91000. 119000. 118000. 103000.  60000.]
car_detection_3D          [ 74000. 113000.  64000.  89000.  62000.]
car_detection_BEV         [112000.  76000.  91000.  74000.  58000.]
car_heading_3D            [ 74000. 113000.  64000.  91000.  89000.]
car_heading_BEV           [ 91000.  74000.  76000. 105000.  88000.]
```
Average of 5 highest performing checkpoints:
car_detection_3D: ~82%, ~73%, ~67%

Average of 100 highest performing checkpoints:
car_detection_3D: ~76%, ~68%, ~65%

Thanks a lot!

Best Regards,
Tuan

**Comment by mikon1995** [comment]
excuse me ,have you solved this problem now ? my accurarcy of last several checkpoints also changed greatly...and the cyclist acc and pedestrian acc seems opposite to authors
