### ISSUE TITLE
Can not download dataset

### ISSUE THREAD

**Issue by liye228** [kujason/avod#58]
Hello!
which dataset should be downloaded ? the "Download right color images, if you want to use stereo information (12 GB)"   or  "Download left color images of object data set (12 GB)"

By the way, I can not download these dataset by their email  link successfully. It is there any other way to download the dataset for 3d object detection?

thanks

**Comment by melfm** [comment]
Please refer to KITTI's official website to download the dataset, you would need all the object detection related data.
