### ISSUE TITLE
 larger batch size and ground plane creation

### ISSUE THREAD

**Issue by amir-raffiee** [kujason/avod#59]
Hi,

Thanks a lot for sharing your wonderful code. I have couple of questions about your code.

1. Can we use larger batch size for every iteration?
2. what algorithm did you use to create ground plane?

**Comment by kujason** [comment]
1. Currently, only a batch size of 1 is supported, with each sample having its own mini batch.
2. Please see here for more information: https://github.com/kujason/avod/issues/19#issuecomment-375759236
