### ISSUE TITLE
How to generate testing results?

### ISSUE THREAD

**Issue by kzkmnmr** [kujason/avod#6]
I can run all of the instructions, however, I'm not sure how to generate results on the testing dataset for Kitti benchmark submission.
Could you tell me how to do it?

**Comment by AbhinavDS** [comment]
Yes, I have the same query. The issue seems to be lack of ground plane data for testing dataset.
How to generate the ground planes for testing dataset (or any other new data)?

**Comment by OmarBarakat1995** [comment]
Also a code sample for inference on a single example (that is not in the dataset) would be appreciated. Excellent work anyways.

**Comment by kujason** [comment]
The planes are generated with an in-house plane estimation algorithm, and we include the output here for easier training on labelled data. We recommend looking into one of the many other available methods for ground plane estimation to generate these files if needed.

Using a constant ground plane for training is also a viable option, although we would recommend using `a, b, c, d = [0, -1, 0, 1.65]` instead, as the ground plane is in the camera co-ordinate frame, and the camera is 1.65m above the ground (http://www.cvlibs.net/datasets/kitti/setup.php).

**Comment by yzhou-saic** [comment]
In order to repeat the same results as reported in the paper, during testing, should we fix the ground plane as a, b, c, d = [0, -1, 0, 1.65] ? I think most of the people care about this.

**Comment by asharakeh** [comment]
@yzhou-saic you will not get the same results unless you use our ground plane estimation algorithm, which we will not be releasing any time soon.

**Comment by kzkmnmr** [comment]
@kujason @asharakeh thank you for the response.

I manually created text.txt and planes directly with "a, b, c, d = [0, -1, 0, 1.65]" in /Kitti/object, then run

`python avod/experiments/run_inference.py --checkpoint_name='avod_cars_example' --data_split='test' --ckpt_indices=120 --device='0'`

This way works!!

I have other question, how to interpret the output values in /avod/data/outputs/avod_cars_example/predictions/final_predictions_and_scores? 

I put example here: 
`3.91767 1.73724 6.20433 3.30604 1.53459 1.41908 -1.33451 0.99933 0.00000`

I guess these output values are: x, y, z, l, w, h, ry, score, ???.
Am I correct?

Thanks in advance.

**Comment by kujason** [comment]
The output is in `box_3d + score` detection format ([more info here](https://github.com/kujason/avod/wiki/Data-Formats)). To convert to KITTI label format, you can use the provided `scripts/offline_eval/save_kitti_predictions.py` script.

**Comment by kzkmnmr** [comment]
My issue has been solved. Thanks.

**Comment by kargarisaac** [comment]
> @yzhou-saic you will not get the same results unless you use our ground plane estimation algorithm, which we will not be releasing any time soon.
> 
> However, any ground plane estimation algorithm should work in theory.


Hi,
I want to use your algorithm on my own dataset. I have developed an algorithm for ground plane estimation. I cannot find respective part of the code for ground plane estimation. Is it possible to feed my point cloud data with separated ground point (I mean extract points above the ground and feed them directly into the network)? I want to know where is the ground estimation (ground plane usage) in your pipeline?

Thanks
