### ISSUE TITLE
Problem about make evalution: boost/numeric/ublas/matrix.hpp:

### ISSUE THREAD

**Issue by csjxchen** [kujason/avod#60]
Hi, kujason：
    Thank you for sharing your invaluable code! But, I encountered a problem when running run_evaluation.py which is raised by the process of making evaluate_object_3d_offline; I have tried my best to search the solution,but failed. Can you help me? thank you very much

**Comment by kujason** [comment]
Please post your error messages, or else I cannot help you easily. You might need to install libboost, or some other missing packages on your system.

**Comment by EchoMaria123** [comment]
you need to install "boost"
