### ISSUE TITLE
tensorflow 1.7?

### ISSUE THREAD

**Issue by YangBain** [kujason/avod#61]
If I can use the high version tensorflow to run this code? Thanks.

**Comment by villanuevab** [comment]
I am able to run training with Tensorflow r1.8, cuda 9.0, protobuf 3.4.0 (change this last one in requirements.txt)

**Comment by asharakeh** [comment]
I think it is compatible up to 1.8 as far as I have tested. We noticed a slight decrease in computation speed for TF > 1.3, but the results are almost identical.

**Comment by villanuevab** [comment]
@asharakeh, computation speed during training, inference, or both?

**Comment by asharakeh** [comment]
Both. Usually training ~ 2x inference.
