### ISSUE TITLE
Why use two different networks in rpn class and regression part ?

### ISSUE THREAD

**Issue by AbuZekry** [kujason/avod#64]
In the file rpn_model, there is this part where you create two identical networks with just the output heads are different. These parts are ['cls_fc6', 'cls_fc6_drop', 'cls_fc7', 'cls_fc7_drop', 'cls_fc8'] and ['reg_fc6', 'reg_fc6_drop', 'reg_fc7', 'reg_fc7_drop', 'reg_fc8']. 

They have the same input and exactly the same dimensions, so why not make them common layers and then output two different heads ['cls_fc8/squeezed', 'reg_fc8/squeezed'] ?

**Comment by melfm** [comment]
The two branches are for two separate tasks, classification and regression. Perhaps you can clarify your question a little bit? What do you mean by squeezed?
