### ISSUE TITLE
Vislualization of the 3D Boxes on Point Cloud

### ISSUE THREAD

**Issue by vivekgr92** [kujason/avod#66]
In the results section in the paper, a 3D prediction have been shown on the point cloud. Is there any code that can be used to see the predictions in point cloud.

thanks

**Comment by melfm** [comment]
For the visualization, we used VTK.

**Comment by walzimmer** [comment]
Can you provide the code to create such visualizations with VTK?
![master_71_vis_vtk](https://user-images.githubusercontent.com/22540236/43562845-5acdcb4e-961f-11e8-8957-bd78da276224.png)

**Comment by lucasjinreal** [comment]
good

**Comment by maxwellfrom** [comment]
Hi
Have you realized the visualization above? @walzimmer

**Comment by kujason** [comment]
Visualization and depth completion scripts are available at https://github.com/kujason/scene_vis
