### ISSUE TITLE
code for visualizing feature map

### ISSUE THREAD

**Issue by HandsLing** [kujason/avod#67]
would you like to share your code of visualizing feature map?
i found feature map visualization in your paper.
thx
my email is lck1994@foxmail.com

**Comment by kujason** [comment]
Try uncommenting these lines. The tiled feature maps should show up in TensorBoard.

https://github.com/kujason/avod/blob/b7dcf31e50230c67bcf19ed063549a8b1bc4a785/avod/core/models/rpn_model.py#L269-L278

**Comment by HandsLing** [comment]
thanks a lot
but how can i show this information in tensorboard?
    summary_histograms: True
    summary_img_images: True
    summary_bev_images: True
three options above were changed to True
but nothing in tensorboard

**Comment by HandsLing** [comment]
i solved that issue ,thank you very much

**Comment by ZhengWG** [comment]
> i solved that issue ,thank you very much

Can you explain how to visualizing feature map? Thans a lot！

**Comment by chrisyan** [comment]
Hi HandsLing,
could you tell me how can I get the specific value of the last feature map? Thanks a lot

Best
Chris
