### ISSUE TITLE
Some confusing issues about projecting 3D tensor anchors into image space

### ISSUE THREAD

**Issue by Benzlxs** [kujason/avod#72]
https://github.com/kujason/avod/blob/b7dcf31e50230c67bcf19ed063549a8b1bc4a785/avod/core/anchor_projector.py#L113
I am confusing about this part of code calculating y_corners, for it should be in the similar way of estimating x_corners and z_corners. (x,y,z) should be center point of 3D bounding box, when calculating y_corners, it seems that y is regarded as bottom coordinate of 3D bounding box instead of center points.
Should it be written as:
y_corners = np.array([y + dim_y_half,
                          y + dim_y_half,
                          y + dim_y_half,
                          y + dim_y_half,
                          y - dim_y_half,
                          y - dim_y_half,
                          y - dim_y_half,
                          y - dim_y_half]).T.reshape(1, -1)

Thanks in advance~~

**Comment by asharakeh** [comment]
@Benzlxs this is how kitti defines y, the centroid of the **lower** bottom of the box. Check Kitti Object detection readme for more info.

**Comment by Benzlxs** [comment]
Many thanks,
I DO find this information in the evaluation code instead of readme file.
This small piece information is really vital to my 3D object detector.
Thank you very much.

**Comment by CrazySnailer** [comment]
Thanks for your explainment!
