### ISSUE TITLE
Where is the plane folder in KITTI dataset

### ISSUE THREAD

**Issue by ray2004a** [kujason/avod#74]
Thanks for the sharing. I tried to search the Keyword of **plane**  in KITTI website but still can't find any related of it. It will be very grateful If some body have any idea of this.
It my first time dealing with KITTI dataset, so sorry for this basic question.

**Comment by melfm** [comment]
Please follow the readme instructions as it provides a link to the planes. Also this [issue](https://github.com/kujason/avod/issues/19) is relevant.

**Comment by giangdip2410** [comment]
@melfm  : could you please share a permission for your google drive link ? I can not access due to not having permission. Thank you.
