### ISSUE TITLE
About out-of-range projected image coordinates

### ISSUE THREAD

**Issue by Benzlxs** [kujason/avod#75]
https://github.com/kujason/avod/blob/b7dcf31e50230c67bcf19ed063549a8b1bc4a785/avod/core/anchor_projector.py#L137

In the nchor_projector.py, it seems that you fail to consider the situation where projected image coordinates are out of image boundary. Should the code be corrected into following ones:

    # TODO, remove out-of-boundary points                                        
    i_axis_min_points = np.amin(pts_2d[0, :].reshape(-1, 8), axis=1)             
    mask_i_min = i_axis_min_points < 0   ## remove negative                      
    i_axis_min_points[mask_i_min] = 0                                            
                                                                                 
    j_axis_min_points = np.amin(pts_2d[1, :].reshape(-1, 8), axis=1)             
    mask_j_min = j_axis_min_points < 0     ## remove negative                                         
    j_axis_min_points[mask_j_min] < 0                                            
                                                                                 
    i_axis_max_points = np.amax(pts_2d[0, :].reshape(-1, 8), axis=1)             
    mask_i_max = i_axis_max_points > image_shape_w -1                            
    i_axis_max_points[mask_i_max] = image_shape_w - 1                            
                                                                                 
    j_axis_max_points = np.amax(pts_2d[1, :].reshape(-1, 8), axis=1)             
    mask_j_max = j_axis_max_points > image_shape_h - 1                           
    j_axis_max_points[mask_j_max] = image_shape_h - 1

**Comment by kujason** [comment]
We decided this was not required since TensorFlow's `crop_and_resize` operation extrapolates 0s for pixels outside the image boundary (https://www.tensorflow.org/api_docs/python/tf/image/crop_and_resize). Boundary clipping is only used when projecting the final 3D detection boxes to get 2D detections.
