### ISSUE TITLE
dataset location

### ISSUE THREAD

**Issue by zuowanghanguang** [kujason/avod#76]
hello:
I am runing the code on sever .And when run the bash 'python scripts/preprocessing/gen_mini_batches.py'
,the problem occur that'Dataset path does not exist: /root/Kitti/object'.So, I want to know what i need to change  in the code ,and my dataset should be placed to where.Thanks for answer!

**Comment by kujason** [comment]
The KITTI data should be placed in `/home/<username>/Kitti/object`, not `/root/Kitti/object`

**Comment by deeplearning666** [comment]
@zuowanghanguang 
hello! I has met the same problem with you! Could you tell me how to solve it? 
Thanks for answer!

**Comment by zuowanghanguang** [comment]
@deeplearning666 hi.sorry to late.it is a easy  problem.you can just make a soft link in the sever .you can do this:join in the sever,and make sure you are in root place,that means the terminate must like this ~: ;then you can make a soft link .you should be sure that you structure of datasets must be true!

**Comment by kkyan1995** [comment]
@deeplearning666  hello,l do not understand the issue that @zuowanghanguang deal with , i have the problem you met ,have you ever solve it with another issue?
Thank you for answer!
