### ISSUE TITLE
Enable data augmentation during Evaluation

### ISSUE THREAD

**Issue by chenyez** [kujason/avod#79]
Thank you for sharing the code, it's been very helpful!

Now I have a question about data augmentation, in run_evaluation.py, line53:

    # Remove augmentation during evaluation
    dataset_config.aug_list = []

My purpose is to add some noise to the data to test the robustness of the architecture. As I see during data augmentation pca jittering has already add some noise to the image, I know the purpose for pca jittering is for data augmentation, but I want to see how the network can defend data with that level of "noise".

So I tried to disable this line, so that during evaluation I can still get augmented data into network. However, when I commented this line, I found out that the evaluation 3D car detection AP is very low, around 0.03%(I'v trained for 100K iterations). The config I use is pyramid_cars_with_aug_example. rpn_fusion_method: 'mean', avod fusion_method:'mean', fusion_type='deep'.

Is there anything I did wrong or could you please tell me which might be the reason for this?

Thanks again and looking forward to your reply!

**Comment by kujason** [comment]
During evaluation, samples are evaluated in order. If you leave augmentation on during evaluation, it seems like you might be evaluating on flipped samples.

**Comment by chenyez** [comment]
Augmentation contains 'Flipping and PCA Jittering' within the 'pyramid_cars_with_aug_example.config' file. Either for training or evaluation, I think firstly the labels are also augmented, then the network used the augmented samples to calculate loss during training processing, I just don't understand why can't it get an accurate result when doing evaluation on these augmented samples?
