### ISSUE TITLE
Recursive git clone fails

### ISSUE THREAD

**Issue by fmigneault** [kujason/avod#8]
This command fails, with unknown publickey error from the wavedata submodule:
```
git clone https://github.com/kujason/avod --recurse-submodules
```
But this repo can correctly be cloned within the just cloned AVOD repo with:
```
cd avod
git clone https://github.com/kujason/wavedata
```
Maybe some setting is incorrect somewhere?

**Comment by kujason** [comment]
What version of Git are you using? This stackoverflow answer may be related:
https://stackoverflow.com/a/4438292

**Comment by fmigneault** [comment]
git version 2.7.4 (version that was installed with apt-get)

**Comment by fmigneault** [comment]
I have tried with latest git version 2.16.2, same issue.

**Comment by lihua213** [comment]
I got the same issue, is there a good solution?

**Comment by YaduKini** [comment]
Hi,
 
I'm getting this error when I run the command _git submodule update --init --recursive_

fatal: could not create work tree dir 'wavedata': Permission denied
fatal: clone of 'git@github.com:kujason/wavedata.git' into submodule path 'wavedata' failed

and I'm getting the below error when i run the same command with sudo:

Cloning into 'wavedata'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kujason/wavedata.git' into submodule path 'wavedata' failed

wavedata folder is not being created. Please help.

**Comment by songanz** [comment]
Did you setup ssh correctly?

**Comment by YaduKini** [comment]
@songanz i fixed the issue. Thanks.

**Comment by qchenclaire** [comment]
> @songanz i fixed the issue. Thanks.

Hi, how did you solve the issue? I am having the same issue

**Comment by sarimmehdi** [comment]
This problem hasn't been solved, please explain how you fixed it. Thank you

**Comment by kujason** [comment]
See https://github.com/kujason/avod/issues/173
