### ISSUE TITLE
ImportError: No module named 'wavedata.tools'

### ISSUE THREAD

**Issue by maryumjam** [kujason/avod#80]
cuda 9.0 , tensorflow 1.3 , python 3.7 I have no idea whats wrong
python3 scripts/preprocessing/gen_mini_batches.py
Traceback (most recent call last):
  File "scripts/preprocessing/gen_mini_batches.py", line 6, in <module>
    from avod.builders.dataset_builder import DatasetBuilder
  File "/mnt/c/Windows/System32/avod/avod/builders/dataset_builder.py", line 6, in <module>
    from avod.datasets.kitti.kitti_dataset import KittiDataset
  File "/mnt/c/Windows/System32/avod/avod/datasets/kitti/kitti_dataset.py", line 10, in <module>
    from wavedata.tools.core import calib_utils
ImportError: No module named 'wavedata.tools'

**Comment by kujason** [comment]
Do you have the `wavedata` submodule initialized? Please try
```
git submodule update --init --recursive
```
and make sure the `wavedata` folder is added to your python path

**Comment by maryumjam** [comment]
Hey I tried to doing that and it always failed so I did something like you can seen in screenshot attached one more thing i am using Windows subsystem linux but I had same issue with ubuntu with VM as well
and I did set python varriable
 like this since avod folder is in my home directory.
![screenshot 5](https://user-images.githubusercontent.com/26106614/42679419-4fe438be-869b-11e8-9d5e-b8fe903de008.png)

export PYTHONPATH=$PYTHONPATH:'/avod'
export PYTHONPATH=$PYTHONPATH:'/avod/wavedata'

**Comment by maryumjam** [comment]
I figured out the issue and sorted it out its suppose to be /home/username/avod/wavedata.

**Comment by arxidinakbar** [comment]
@maryumjam There is no such function named 'tools' in wavedata, aren't they?
Just can't import such function.
