### ISSUE TITLE
How about dense depth map

### ISSUE THREAD

**Issue by Yc174** [kujason/avod#81]
I observe that there are reserved interfaces for depth maps in the program. Have you tried to use dense map for AOVD，such as use sun-rgbd dataset？If tried, how about the results. Thank you @kujason @fmigneault @melfm @asharakeh

**Comment by kujason** [comment]
Yes, we tried using dense depth maps from LiDAR and the results were similar or slightly worse for cars. There are several recent papers that have tried using AVOD with stereo depth and monocular depth maps with reasonable success.
