### ISSUE TITLE
ROS node

### ISSUE THREAD

**Issue by yukkysaito** [kujason/avod#83]
Are avod ROS node public?
If it is available, could you tell me how to use it?

**Comment by melfm** [comment]
No the ROS wrappers are not publicly available. However its not difficult to set up, you would need to define your own dataset wrapper and make sure you convert the data into the format required by the network.

**Comment by yukkysaito** [comment]
Thank you!

**Comment by kargarisaac** [comment]
> No the ROS wrappers are not publicly available. However its not difficult to set up, you would need to define your own dataset wrapper and make sure you convert the data into the format required by the network.

Hi,
I try to use the BEV generation part as a ros node. There are some errors. I guess because of difference between py3 and py2. Do you have any suggestion to solve such problems?
Thanks

**Comment by maxwellfrom** [comment]
Have you realized avod ros node? @yukkysaito

**Comment by kargarisaac** [comment]
Writing a ros node for avod inference seems very confusing. I cannot figure out how to feed data. How can we write a node that subscribes to some topics for rgb and bev images? The model object needs created dataset object from datasetbuilder. 
Does any body did it?
