### ISSUE TITLE
Orientation Problem

### ISSUE THREAD

**Issue by FrankCAN** [kujason/avod#85]
Hi Kujason,
Thanks for your code and paper, it really helped me a lot. But I have some problem for the orientation indication issue, why is the orientation only one black line as attached picture as below, what does this black line mean for the orientation? Thanks a lot for your help.

![orientation](https://user-images.githubusercontent.com/33595530/42995188-17e40d96-8c08-11e8-811f-d2e5d79ca407.png)

**Comment by kujason** [comment]
The black line is showing the forward direction of the object.
