### ISSUE TITLE
Planes

### ISSUE THREAD

**Issue by radler12** [kujason/avod#86]
Can you explain what contais planes folder in your framework and how you generate these files?

Best regards,

**Comment by walzimmer** [comment]
The planes folder in the KITTI dataset contains the ground planes of the ego vehicle. For each camera image (frame) you have a corresponding ground plane that was calculated from the IMU data (roll, pitch, yaw) of your vehicle. 
The format is the following:

Width 4
Height 1
-7.051739e-03 -9.997791e-01 -1.980150e-02 1.680367e+00

The vector [-7.051739e-03 -9.997791e-01 -1.980150e-02] defines the normal vector of the plane. It is almost [0 -1 0] which means that the plane is nearly even. The forth value 1.68 is the height of the camera relative to the plane.

The ground planes are used to calculate the 3d anchor grid.

**Comment by villanuevab** [comment]
What are the Width and Height values used for?
```
Width 4
Height 1
``` 
Thanks for your time!

**Comment by Manyunze** [comment]
@villanuevab This is the dimension of the plane matrix., which is 4 x 1 like [-7.051739e-03, -9.997791e-01, -1.980150e-02, 1.680367e+00].

**Comment by FrankCAN** [comment]
@walzimmer For the detection training data, where did you find the IMU data for ground plane generation? And for the vector [-7.051739e-03 -9.997791e-01 -1.980150e-02 1.680367e+00], I think the fourth parameter is 1.65m, but how did you calculate your fourth parameter which is 1.680367e+00, and why doesn't it be a constant value?

Many thanks for your help, very much appreciate for that.

**Comment by lucasjinreal** [comment]
Does anyone knows how to using a constance ground plane for prediction a video sequence data?

**Comment by kargarisaac** [comment]
is it possible to do ground removing before AVOD and feed the points without ground into AVOD model? Is there any flag to disable using ground plane in AVOD?

**Comment by mengmengQi** [comment]
> The planes folder in the KITTI dataset contains the ground planes of the ego vehicle. For each camera image (frame) you have a corresponding ground plane that was calculated from the IMU data (roll, pitch, yaw) of your vehicle.
> The format is the following:
> Width 4
> Height 1
> -7.051739e-03 -9.997791e-01 -1.980150e-02 1.680367e+00
> The vector [-7.051739e-03 -9.997791e-01 -1.980150e-02] defines the normal vector of the plane. It is almost [0 -1 0] which means that the plane is nearly even. The forth value 1.68 is the height of the camera relative to the plane.
> The ground planes are used to calculate the 3d anchor grid.

Hi, in fact the fourth parameter change all the time, perhaps it isn't the height of camera. Have you resolved the problem?

**Comment by staillyd** [comment]
@mengmengQi it is "the height of the camera **relative to the plane**."

**Comment by staillyd** [comment]
> The planes folder in the KITTI dataset contains the ground planes of the ego vehicle. For each camera image (frame) you have a corresponding ground plane that was calculated from the IMU data (roll, pitch, yaw) of your vehicle.
> The format is the following:
> 
> Width 4
> Height 1
> -7.051739e-03 -9.997791e-01 -1.980150e-02 1.680367e+00
> 
> The vector [-7.051739e-03 -9.997791e-01 -1.980150e-02] defines the normal vector of the plane. It is almost [0 -1 0] which means that the plane is nearly even. The forth value 1.68 is the height of the camera relative to the plane.
> 
> The ground planes are used to calculate the 3d anchor grid.

@walzimmer Assuming that the unit normal vector of the plane is in the format [x, y, z]. It seems not the coordinate system in which the IMU is located. would you tell me what the coordinate system of plane looks like? 
- all camera heights: 1.65m
- velodyne laserscanner height: 1.73m
- GPS/IMU height: 0.93m
![passat_sensors_920](https://user-images.githubusercontent.com/21957896/74501165-3a139400-4f24-11ea-8c1f-3b4699063258.png)

Best regards.

**Comment by Petros626** [comment]
@walzimmer would it be possible to estimate z and height with the ground planes? I saw approaches like BirdNet+, which use some `.txt` files in their 3D Box regression task, but not sure, if they mean these plane files.
(https://github.com/AlejandroBarrera/birdnet2/blob/5ceed811b289796d7d7420a064ecb079c80801ab/tools/val_net_BirdNetPlus.py#L123).
