### ISSUE TITLE
Protoc error: Expected "required", "optional", or "repeated".

### ISSUE THREAD

**Issue by nidhitvaishnav** [kujason/avod#87]
Hi,

When I run the command
`sh avod/protos/run_protoc.sh` or 
`protoc avod/protos/*.proto --python_out=.`
It is providing me the error:

```
avod/protos/kitti_utils.proto:24:5: Expected "required", "optional", or "repeated".
avod/protos/kitti_utils.proto:24:25: Missing field number.
avod/protos/kitti_dataset.proto: Import "avod/protos/kitti_utils.proto" was not found or had errors.
avod/protos/kitti_dataset.proto:39:14: "KittiUtilsConfig" is not defined.

```

 I have Ubuntu 14.04, Tensorflow-gpu 1.3.0 and protobuf 3.4.0 (protobuf 3.2.0 is not suported with given tensorflow version, Though I have tried 3.2.0, 3.3.0, 3.6.0, 3.5.1 and 3.5.2 version of protobuf). 
Please post suggestion if you have any.

**Comment by nidhitvaishnav** [comment]
So I could not resolve this issue. So I moved to Ubuntu 18.04 (latest available version). Now my code is able to run with above tensor flow and protobuf configuration.

**Comment by oaix** [comment]
Ubuntu 14.04 appears the same error. My environment is Tensorflow-gpu 1.3.0, and protobuf 3.7.0. Does anyone solve this problem for ubuntu 14.04? Thanks.

> Hi,
> 
> When I run the command
> `sh avod/protos/run_protoc.sh` or
> `protoc avod/protos/*.proto --python_out=.`
> It is providing me the error:
> 
> ```
> avod/protos/kitti_utils.proto:24:5: Expected "required", "optional", or "repeated".
> avod/protos/kitti_utils.proto:24:25: Missing field number.
> avod/protos/kitti_dataset.proto: Import "avod/protos/kitti_utils.proto" was not found or had errors.
> avod/protos/kitti_dataset.proto:39:14: "KittiUtilsConfig" is not defined.
> ```

**Comment by oaix** [comment]
@nidhitvaishnav 
I solve this problem referring to https://github.com/tensorflow/models/issues/1834. This error occurs because of the system can't find protoc which is executable. So we only need to download the executable protoc to somewhere, then use it directly. I select protobuf 3.6.0 [protoc-3.6.0-linux-x86_64.zip
](https://github.com/protocolbuffers/protobuf/releases?after=v3.6.1) which works to me.

```sh
# assume protoc-3.6.0-linux-x86_64.zip saved at ~/
mkdir ~/avod/protoc_3_6_0
mv ~/protoc-3.6.0-linux-x86_64.zip ~/avod/protoc_3_6_0
cd ~/avod/protoc_3_6_0
unzip protoc-3.6.0-linux-x86_64.zip
cd ..
./protoc_3_6_0/bin/protoc avod/protos/*proto --python_out=.

```
