### ISSUE TITLE
Failed to parse YAML : mapping values are not allowed here

### ISSUE THREAD

**Issue by DenisFromRussia** [kujason/avod#88]
Hi, if i try to submit your model to gcloud with config=avod_cars_examples.config next problem appears : 
"Failed to parse YAML : mapping values are not allowed here in line 5, column 15".
The 5th line looks so:     model_name: 'avod_model'.
Hence the problem is with the colon(there is a space after it). Do you have any suggestions how to solve this problem?

**Comment by kujason** [comment]
Sorry, I have no suggestions. This seems like an unrelated issue with gcloud and yaml.
