### ISSUE TITLE
How to detect vehicle and people simultaneously

### ISSUE THREAD

**Issue by ktxu1224** [kujason/avod#9]
1. As described in paper, the network detect vehicle and people separately, so how to detect both of them simultaneously?
2. Whether the config file avod/configs/pyramid_cars_with_aug_example.config refers to the project AVOD-FPN ranking first in ketti?
Thx!

**Comment by asharakeh** [comment]
1. We do not provide scripts to train all object instances. You will need to write your own batch creation to include all classes + modify the final classification layer to take into consideration 3 classes. 

2. Yes

**Comment by ktxu1224** [comment]
Ok, thx! That means I need to modify the following files orderly: 
1. avod/configs/mb_preprocessing/rpn_[class].config
2.scripts/preprocessing/gen_mini_batches.py
but I find out the file gen_mini_batches.py can gererate both vehicle and people batches simultaneously.  Right?
And then I need to create a new config file like ones inside avod/configs, right?
And whether "modify the final classification layer" means that I need to modify the network structure?

**Comment by asharakeh** [comment]
Yes for both questions. You will need to modify the structure of the final layer to output 4 class scores for [car, ped, cyc, background] classes.

**Comment by RMobina** [comment]
> @asharakeh Ok, thx! That means I need to modify the following files orderly?
> 
>     1. avod/configs/mb_preprocessing/rpn_[class].config;
>        2.scripts/preprocessing/gen_mini_batches.py;
>        but I find out the file gen_mini_batches.py can gererate both vehicle and people batches simultaneously.  Right?
>        And then I need to create a new config file like ones inside avod/configs, right?
>        Second Question,  whether "modify the final classification layer" means that I need to modify the network structure?



> Yes for both questions. You will need to modify the structure of the final layer to output 4 class scores for [car, ped, cyc, background] classes.

could you please explain in more detail how to modify the structure of the final layer to output 4 class scores for [car, ped, cyc, background] classes?specifying [car, ped, cyc] in avod/configs is not sufficient?
