### ISSUE TITLE
AVOD Model Output Nodes? 

### ISSUE THREAD

**Issue by villanuevab** [kujason/avod#97]
I am looking at the attached graph on TensorBoard. I assumed avod_nms was the output node, but it seems like the gather operations are regarded as nodes in the graph as well. Does this mean that the output nodes are these? 

```
avod_nms/GatherV2
avod_nms/GatherV2_1
avod_nms/GatherV2_2
avod_nms/GatherV2_3
avod_nms/GatherV2_4
avod_nms/GatherV2_5
```

Thanks for your help. I'm trying to freeze the graph and looking for the correct output_nodes to do this with. 

![screen shot 2018-08-07 at 1 22 20 pm](https://user-images.githubusercontent.com/3021974/43800377-fd4f9b08-9a44-11e8-87b9-4066d6e17618.png)

**Comment by kujason** [comment]
The `tf.gather` operation is used to gather output from several different nodes, using the indices returned by `tf.image.non_max_suppression`
https://github.com/kujason/avod/blob/b7dcf31e50230c67bcf19ed063549a8b1bc4a785/avod/core/models/avod_model.py#L504-L545

**Comment by Priyashbhugra** [comment]
Hi are you able to find the output node name. I am trying to do the same. please let me know the exact output names if you were able to find.

**Comment by kujason** [comment]
The output nodes are the gather nodes, and their names will be automatically generated by Tensorflow since we do not specify their names directly.
