### ISSUE TITLE
Question of the accuracy for the network with only RGB as input source

### ISSUE THREAD

**Issue by biligogo** [kujason/avod#99]
To Authors and anyone who is interested:

I tested the accuracy of the AVOD with only RGB image as input. I achieved that goal by multiplying the lidar data by 0. However, the result is really bad. The accuracy is around 11%. Can you tell me is there any reason that you think might answer this result? 

Thank you @kujason  @fmigneault  @melfm  @asharakeh. 
Thanks for the help. Appreciate it!

**Comment by kujason** [comment]
The RGB image does not contain depth information, so localization of the objects will be poor compared to using the LiDAR points.
